const translations = {
  en: {
    "common.tagline": "TravelKo",
    "seo.title": "TravelKo - Discover Korea | Best Travel Guide",
    "seo.description": "Discover the best travel spots in Korea recommended by the community. Food, attractions, cafes, nature and more with interactive map.",
    "nav.home": "Home",
    "nav.explore": "Explore",
    "nav.lang": "한국어",

    "app.title": "Discover Korea",
    "app.subtitle": "Travel spots recommended by the community",
    "app.searchPh": "Search places...",
    "app.catAll": "All",
    "app.catFood": "Food",
    "app.catAttraction": "Attractions",
    "app.catCafe": "Cafe",
    "app.catNature": "Nature",
    "app.catShopping": "Shopping",
    "app.catNightlife": "Nightlife",
    "app.catHalal": "Halal Food",
    "app.catMosque": "Mosque",
    "app.catVegetarian": "Vegetarian",
    "app.muslimToggle": "Muslim Friendly",
    "app.muslimDesc": "+ Halal restaurants & mosques included",
    "app.viewMap": "Map",
    "app.viewList": "List",
    "app.regionAll": "All Regions",
    "app.regionSeoul": "Seoul",
    "app.regionBusan": "Busan",
    "app.regionJeju": "Jeju",
    "app.regionIncheon": "Incheon",
    "app.regionGyeonggi": "Gyeonggi",
    "app.regionOther": "Other",
    "app.featured": "Featured",
    "app.rating": "Rating",
    "app.views": "Views",
    "app.noResults": "No spots found. Try a different filter.",
    "app.loading": "Loading spots...",
    "app.loadMore": "Load More",
    "app.openNaver": "Open in Naver Map",
    "app.openGoogle": "Open in Google Map",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Share a Spot",
    "app.submitTitle": "Share a Travel Spot",
    "app.submitNotice": "Your submission will appear after admin review.",
    "app.placeLabel": "Place Name",
    "app.placePh": "e.g. Gyeongbokgung Palace",
    "app.categoryLabel": "Category",
    "app.descLabel": "Your Review",
    "app.descPh": "Share your experience...",
    "app.addressLabel": "Address",
    "app.addressPh": "Search address...",
    "app.searchBtn": "Search",
    "app.instagramLabel": "Instagram Tags",
    "app.instagramPh": "@username or #hashtag",
    "app.authorLabel": "Your Name",
    "app.authorPh": "Your name",
    "app.cancelBtn": "Cancel",
    "app.submitBtn": "Submit",
    "app.submitted": "Thank you! Your spot will appear after admin review.",
    "app.submitError": "Failed to submit. Please try again.",
    "app.mapError": "Map could not be loaded.",

    "auth.signIn": "Sign In",
    "auth.signOut": "Sign Out",
    "auth.signInWith": "Sign in with Google",
    "auth.welcome": "Welcome",

    "bookmark.wantToVisit": "Want to Visit",
    "bookmark.interested": "Interested",
    "bookmark.remove": "Remove",
    "bookmark.saved": "Saved!",
    "bookmark.removed": "Removed",
    "bookmark.loginRequired": "Sign in to save spots",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "No saved spots yet",
    "bookmark.wantToVisitEmpty": "No 'Want to Visit' spots yet",
    "bookmark.interestedEmpty": "No 'Interested' spots yet",

    "planner.title": "AI Travel Planner",
    "planner.desc": "Plan your trip based on your saved spots",
    "planner.days": "Trip Duration",
    "planner.daysUnit": "days",
    "planner.budget": "Budget",
    "planner.budgetBudget": "Budget-friendly",
    "planner.budgetModerate": "Moderate",
    "planner.budgetLuxury": "Luxury",
    "planner.style": "Travel Style",
    "planner.styleRelaxed": "Relaxed",
    "planner.styleBalanced": "Balanced",
    "planner.stylePacked": "Packed",
    "planner.spots": "Spots to Include",
    "planner.generate": "Generate Plan",
    "planner.generating": "Creating your travel plan...",
    "planner.result": "Your Travel Plan",
    "planner.retry": "Generate Again",
    "planner.close": "Close",
    "planner.noSpots": "Save spots as 'Want to Visit' first",
    "planner.error": "Failed to generate plan. Please try again.",
    "planner.rateLimit": "Daily limit reached ({limit} plans/day). Try again tomorrow!",
    "planner.remaining": "{n} plans remaining today",
    "planner.btn": "Plan Trip",
    "planner.save": "Save Plan",
    "planner.saved": "Plan saved!",
    "planner.myPlans": "My Plans",
    "planner.compare": "Compare",
    "planner.comparePlans": "Compare Plans",
    "planner.noSavedPlans": "No saved plans yet",
    "planner.deletePlan": "Delete",
    "planner.viewPlan": "View",
    "planner.planTitle": "{days}-Day Trip",
    "planner.spots_count": "{n} spots",
    "planner.savedLocal": "Saved on this device",
    "planner.selectToCompare": "Select 2-3 plans to compare",
    "planner.back": "Back",
    "planner.namePrompt": "Name this plan:",
    "planner.share": "Share",
    "planner.shareTitle": "Share this plan",
    "planner.copyLink": "Copy Link",
    "planner.sharing": "Creating share link...",

    "tips.title": "Korea Travel Guide",
    "tips.officialInfo": "Official travel information provided by Korea Tourism Organization",
    "tips.transport": "Transportation",
    "tips.transportDesc": "Korea has an excellent public transport system. Use T-money card for subway, bus, and taxi.",
    "tips.subway": "Subway",
    "tips.subwayInfo": "Base ₩1,400 (T-money), distance-based extra",
    "tips.bus": "City Bus",
    "tips.busInfo": "₩1,500 (T-money)",
    "tips.taxi": "Taxi",
    "tips.taxiInfo": "Base ₩4,800, late night +20%",
    "tips.ktx": "KTX (High-speed Rail)",
    "tips.ktxInfo": "Seoul↔Busan ₩59,800 · Seoul↔Daejeon ₩23,700",
    "tips.airport": "Airport Express (AREX)",
    "tips.airportInfo": "Incheon Airport↔Seoul Station ₩9,500 (Express)",
    "tips.bookKorail": "Book KTX / Train Tickets",
    "tips.bookBus": "Book Express Bus Tickets",
    "tips.moreTransport": "More Transport Info",
    "tips.meals": "Meal Prices (Approximate)",
    "tips.budget": "Budget (~₩10,000)",
    "tips.budgetDesc": "Kimbap, street food, convenience stores",
    "tips.moderate": "Moderate (₩10,000~30,000)",
    "tips.moderateDesc": "Korean BBQ, bibimbap restaurants, cafes",
    "tips.luxury": "Luxury (₩30,000+)",
    "tips.luxuryDesc": "Hanwoo beef, fine dining, omakase",
    "tips.useful": "Useful Tips",
    "tips.tmoney": "Get a T-money card at any convenience store (₩4,000) for subway, bus & taxi",
    "tips.tipping": "Tipping is not customary in Korea",
    "tips.atm": "ATMs available at all convenience stores (CU, GS25, 7-Eleven)",
    "tips.emergency": "Emergency: 112 (Police), 119 (Fire/Ambulance)",
    "tips.hotline": "1330 Korea Travel Hotline — 24/7, multilingual support",
    "tips.visitKorea": "Visit Korea — Official Tourism Guide",
    "tips.lastUpdated": "Prices as of Jan 2026 · Source: Korea Tourism Organization",
    "tips.btn": "Travel Guide",
    "tips.taxiGuide": "Taxi Guide for Foreigners",
    "tips.taxiIntro": "Taxis in Korea are safe, clean, and affordable. Here's everything you need to know based on real traveler experiences.",
    "tips.taxiApp": "Recommended Apps",
    "tips.taxiAppDesc": "K-ride (by Kakao, 100% English UI, global credit cards) or TABA (Seoul's official foreigner taxi app). No Korean phone number needed.",
    "tips.taxiHail": "Hailing a Taxi",
    "tips.taxiHailDesc": "Look for taxis with red '빈차' (vacant) light. Raise your hand at the curb. Show your destination in Korean on your phone (use Naver Map or KakaoMap).",
    "tips.taxiTypes": "Taxi Types",
    "tips.taxiRegular": "Regular (orange/white/silver) — Base ₩4,800",
    "tips.taxiDeluxe": "Deluxe/Mobeom (black, yellow stripe) — Base ₩7,000, no late-night surcharge",
    "tips.taxiInternational": "International Taxi — English/Chinese/Japanese speaking drivers",
    "tips.taxiPay": "Payment",
    "tips.taxiPayDesc": "Cash, credit card (Visa/Mastercard), T-money, KakaoPay, Samsung Pay all accepted. No tip needed.",
    "tips.taxiSafety": "Safety Tips",
    "tips.taxiSafety1": "Always check the meter is running when you get in",
    "tips.taxiSafety2": "Use official taxi stands at airports — never accept rides from people approaching you inside terminals",
    "tips.taxiSafety3": "Decline flat-rate offers — the meter is almost always cheaper",
    "tips.taxiSafety4": "Official taxis have yellow license plates (아, 바, 사, 자)",
    "tips.taxiSafety5": "Report issues: call 1330 (Tourism Hotline, multilingual)",
    "tips.taxiCost": "Approximate Costs",
    "tips.taxiCostAirport": "Incheon Airport → Seoul: ₩65,000~80,000 + toll ₩2,000",
    "tips.taxiCostCity": "Within Seoul (10 min): ₩6,000~10,000",
    "tips.taxiCostNight": "Late night (22:00-04:00): +20% surcharge (regular taxi only)",
    "tips.taxiDoor": "Doors are NOT automatic — open and close them yourself (unlike Japan)",
    "tips.taxiReviews": "Real Traveler Reviews",
    "tips.taxiKride": "Download K-ride",
    "tips.taxiTaba": "Download TABA",

    "footer.text": "© 2026 TravelKo by KoInfo. Discover Korea together.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
  },

  ko: {
    "common.tagline": "트래블코",
    "seo.title": "트래블코 - 한국 여행 가이드 | 커뮤니티 추천 명소",
    "seo.description": "커뮤니티가 추천하는 한국 최고의 여행 명소를 발견하세요. 맛집, 관광지, 카페, 자연 등 인터랙티브 지도와 함께.",
    "nav.home": "홈",
    "nav.explore": "탐색",
    "nav.lang": "English",

    "app.title": "한국을 발견하세요",
    "app.subtitle": "커뮤니티가 추천하는 여행 명소",
    "app.searchPh": "장소 검색...",
    "app.catAll": "전체",
    "app.catFood": "맛집",
    "app.catAttraction": "관광지",
    "app.catCafe": "카페",
    "app.catNature": "자연",
    "app.catShopping": "쇼핑",
    "app.catNightlife": "나이트라이프",
    "app.catHalal": "할랄 음식",
    "app.catMosque": "기도실/모스크",
    "app.catVegetarian": "채식",
    "app.muslimToggle": "무슬림 친화",
    "app.muslimDesc": "+ 할랄 식당 & 기도실 포함",
    "app.viewMap": "지도",
    "app.viewList": "목록",
    "app.regionAll": "전체 지역",
    "app.regionSeoul": "서울",
    "app.regionBusan": "부산",
    "app.regionJeju": "제주",
    "app.regionIncheon": "인천",
    "app.regionGyeonggi": "경기",
    "app.regionOther": "기타",
    "app.featured": "추천",
    "app.rating": "평점",
    "app.views": "조회",
    "app.noResults": "검색 결과가 없습니다. 다른 필터를 시도해 보세요.",
    "app.loading": "불러오는 중...",
    "app.loadMore": "더 보기",
    "app.openNaver": "네이버 지도에서 열기",
    "app.openGoogle": "구글 지도에서 열기",
    "app.mapNaver": "네이버 지도",
    "app.mapGoogle": "구글 지도",
    "app.shareSpot": "여행지 공유",
    "app.submitTitle": "여행지 공유하기",
    "app.submitNotice": "관리자 승인 후 게시됩니다.",
    "app.placeLabel": "장소 이름",
    "app.placePh": "예: 경복궁",
    "app.categoryLabel": "카테고리",
    "app.descLabel": "리뷰",
    "app.descPh": "경험을 공유하세요...",
    "app.addressLabel": "주소",
    "app.addressPh": "주소 검색...",
    "app.searchBtn": "검색",
    "app.instagramLabel": "인스타그램 태그",
    "app.instagramPh": "@계정 또는 #해시태그",
    "app.authorLabel": "작성자",
    "app.authorPh": "이름",
    "app.cancelBtn": "취소",
    "app.submitBtn": "제출",
    "app.submitted": "감사합니다! 관리자 승인 후 게시됩니다.",
    "app.submitError": "제출에 실패했습니다. 다시 시도해 주세요.",
    "app.mapError": "지도를 불러올 수 없습니다.",

    "auth.signIn": "로그인",
    "auth.signOut": "로그아웃",
    "auth.signInWith": "Google로 로그인",
    "auth.welcome": "환영합니다",

    "bookmark.wantToVisit": "방문할 곳",
    "bookmark.interested": "관심있는 곳",
    "bookmark.remove": "삭제",
    "bookmark.saved": "저장됨!",
    "bookmark.removed": "삭제됨",
    "bookmark.loginRequired": "로그인 후 장소를 저장하세요",
    "bookmark.mySpots": "내 장소",
    "bookmark.noBookmarks": "저장한 장소가 없습니다",
    "bookmark.wantToVisitEmpty": "'방문할 곳'이 없습니다",
    "bookmark.interestedEmpty": "'관심있는 곳'이 없습니다",

    "planner.title": "AI 여행 플래너",
    "planner.desc": "저장한 장소를 기반으로 여행을 계획하세요",
    "planner.days": "여행 기간",
    "planner.daysUnit": "일",
    "planner.budget": "예산",
    "planner.budgetBudget": "저예산",
    "planner.budgetModerate": "보통",
    "planner.budgetLuxury": "럭셔리",
    "planner.style": "여행 스타일",
    "planner.styleRelaxed": "여유롭게",
    "planner.styleBalanced": "적당히",
    "planner.stylePacked": "빡빡하게",
    "planner.spots": "포함할 장소",
    "planner.generate": "계획 생성",
    "planner.generating": "여행 계획을 만들고 있습니다...",
    "planner.result": "여행 계획",
    "planner.retry": "다시 생성",
    "planner.close": "닫기",
    "planner.noSpots": "먼저 '방문할 곳'에 장소를 저장하세요",
    "planner.error": "계획 생성에 실패했습니다. 다시 시도해 주세요.",
    "planner.rateLimit": "일일 사용 한도에 도달했습니다 (하루 {limit}회). 내일 다시 시도해 주세요!",
    "planner.remaining": "오늘 {n}회 남음",
    "planner.btn": "여행 계획",
    "planner.save": "계획 저장",
    "planner.saved": "계획이 저장되었습니다!",
    "planner.myPlans": "내 계획",
    "planner.compare": "비교",
    "planner.comparePlans": "계획 비교",
    "planner.noSavedPlans": "저장된 계획이 없습니다",
    "planner.deletePlan": "삭제",
    "planner.viewPlan": "보기",
    "planner.planTitle": "{days}일 여행",
    "planner.spots_count": "스팟 {n}개",
    "planner.savedLocal": "이 기기에 저장됨",
    "planner.selectToCompare": "비교할 계획을 2~3개 선택하세요",
    "planner.back": "뒤로",
    "planner.namePrompt": "계획 이름을 입력하세요:",
    "planner.share": "공유",
    "planner.shareTitle": "이 계획 공유하기",
    "planner.copyLink": "링크 복사",
    "planner.sharing": "공유 링크 생성 중...",

    "tips.title": "한국 여행 가이드",
    "tips.officialInfo": "한국관광공사 공식 여행 정보 제공",
    "tips.transport": "교통수단",
    "tips.transportDesc": "한국은 대중교통이 잘 발달되어 있습니다. T-money 카드로 지하철, 버스, 택시 이용 가능.",
    "tips.subway": "지하철",
    "tips.subwayInfo": "기본 ₩1,400 (T-money), 거리비례 추가",
    "tips.bus": "시내버스",
    "tips.busInfo": "₩1,500 (T-money)",
    "tips.taxi": "택시",
    "tips.taxiInfo": "기본 ₩4,800, 심야 20% 할증",
    "tips.ktx": "KTX (고속열차)",
    "tips.ktxInfo": "서울↔부산 ₩59,800 · 서울↔대전 ₩23,700",
    "tips.airport": "공항철도 (AREX)",
    "tips.airportInfo": "인천공항↔서울역 ₩9,500 (직통)",
    "tips.bookKorail": "KTX / 기차표 예매",
    "tips.bookBus": "고속버스 예매",
    "tips.moreTransport": "교통 상세 정보",
    "tips.meals": "식비 (대략적 가격)",
    "tips.budget": "저예산 (~₩10,000)",
    "tips.budgetDesc": "김밥, 분식, 편의점",
    "tips.moderate": "보통 (₩10,000~30,000)",
    "tips.moderateDesc": "한식당, 카페, 삼겹살",
    "tips.luxury": "럭셔리 (₩30,000+)",
    "tips.luxuryDesc": "한우, 파인다이닝, 오마카세",
    "tips.useful": "유용한 팁",
    "tips.tmoney": "편의점에서 T-money 카드(₩4,000) 구매 → 지하철, 버스, 택시에 사용",
    "tips.tipping": "한국에서는 팁 문화가 없습니다",
    "tips.atm": "모든 편의점(CU, GS25, 세븐일레븐)에 ATM 설치",
    "tips.emergency": "긴급: 112(경찰), 119(소방/구급)",
    "tips.hotline": "1330 관광통역안내전화 — 24시간, 다국어 지원",
    "tips.visitKorea": "대한민국 구석구석 — 공식 관광 가이드",
    "tips.lastUpdated": "2026년 1월 기준 · 출처: 한국관광공사",
    "tips.btn": "여행 가이드",
    "tips.taxiGuide": "외국인을 위한 택시 가이드",
    "tips.taxiIntro": "한국의 택시는 안전하고 깨끗하며 저렴합니다. 실제 여행자 후기를 바탕으로 정리한 이용 가이드입니다.",
    "tips.taxiApp": "추천 앱",
    "tips.taxiAppDesc": "K-ride (카카오, 영어 UI, 해외카드 결제) 또는 TABA (서울시 공식 외국인 택시 앱). 한국 전화번호 없이 사용 가능.",
    "tips.taxiHail": "택시 잡기",
    "tips.taxiHailDesc": "'빈차' 빨간불이 켜진 택시에 손을 들어 정차시키세요. 목적지를 네이버 지도나 카카오맵에서 한국어로 보여주세요.",
    "tips.taxiTypes": "택시 종류",
    "tips.taxiRegular": "일반 (주황/흰/은색) — 기본 ₩4,800",
    "tips.taxiDeluxe": "모범 (검정, 노란 띠) — 기본 ₩7,000, 심야 할증 없음",
    "tips.taxiInternational": "국제택시 — 영어/중국어/일본어 가능한 기사",
    "tips.taxiPay": "결제 수단",
    "tips.taxiPayDesc": "현금, 신용카드 (Visa/Mastercard), T-money, 카카오페이, 삼성페이 모두 가능. 팁 불필요.",
    "tips.taxiSafety": "안전 수칙",
    "tips.taxiSafety1": "탑승 시 반드시 미터기 작동 확인",
    "tips.taxiSafety2": "공항에서는 공식 택시 승차장만 이용 — 터미널 안에서 접근하는 호객 절대 거절",
    "tips.taxiSafety3": "정액 제안은 거절 — 미터기가 거의 항상 저렴",
    "tips.taxiSafety4": "공식 택시는 노란 번호판 (아, 바, 사, 자)",
    "tips.taxiSafety5": "문제 발생 시: 1330 (관광통역안내전화, 다국어 지원)",
    "tips.taxiCost": "대략적 비용",
    "tips.taxiCostAirport": "인천공항 → 서울: ₩65,000~80,000 + 통행료 ₩2,000",
    "tips.taxiCostCity": "서울 시내 (10분): ₩6,000~10,000",
    "tips.taxiCostNight": "심야 (22:00-04:00): +20% 할증 (일반택시만)",
    "tips.taxiDoor": "택시 문은 자동이 아닙니다 — 직접 열고 닫으세요 (일본과 다름)",
    "tips.taxiReviews": "실제 이용 후기",
    "tips.taxiKride": "K-ride 다운로드",
    "tips.taxiTaba": "TABA 다운로드",

    "footer.text": "© 2026 TravelKo by KoInfo. 함께 한국을 발견하세요.",
    "footer.privacy": "개인정보처리방침",
    "footer.terms": "서비스 이용약관",
  },

  id: {
    "common.tagline": "TravelKo",
    "seo.title": "TravelKo - Temukan Korea | Panduan Wisata Terbaik",
    "seo.description": "Temukan tempat wisata terbaik di Korea yang direkomendasikan komunitas. Kuliner, atraksi, kafe, alam dan lainnya dengan peta interaktif.",
    "nav.home": "Beranda",
    "nav.explore": "Jelajahi",
    "nav.lang": "한국어",

    "app.title": "Temukan Korea",
    "app.subtitle": "Tempat wisata rekomendasi komunitas",
    "app.searchPh": "Cari tempat...",
    "app.catAll": "Semua",
    "app.catFood": "Kuliner",
    "app.catAttraction": "Wisata",
    "app.catCafe": "Kafe",
    "app.catNature": "Alam",
    "app.catShopping": "Belanja",
    "app.catNightlife": "Hiburan Malam",
    "app.catHalal": "Makanan Halal",
    "app.catMosque": "Masjid",
    "app.catVegetarian": "Vegetarian",
    "app.muslimToggle": "Ramah Muslim",
    "app.muslimDesc": "+ Restoran halal & masjid disertakan",
    "app.viewMap": "Peta",
    "app.viewList": "Daftar",
    "app.regionAll": "Semua Wilayah",
    "app.regionSeoul": "Seoul",
    "app.regionBusan": "Busan",
    "app.regionJeju": "Jeju",
    "app.regionIncheon": "Incheon",
    "app.regionGyeonggi": "Gyeonggi",
    "app.regionOther": "Lainnya",
    "app.featured": "Pilihan",
    "app.rating": "Rating",
    "app.views": "Dilihat",
    "app.noResults": "Tidak ada tempat ditemukan. Coba filter lain.",
    "app.loading": "Memuat...",
    "app.loadMore": "Muat Lagi",
    "app.openNaver": "Buka di Naver Map",
    "app.openGoogle": "Buka di Google Map",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Bagikan Tempat",
    "app.submitTitle": "Bagikan Tempat Wisata",
    "app.submitNotice": "Akan tampil setelah disetujui admin.",
    "app.placeLabel": "Nama Tempat",
    "app.placePh": "contoh: Istana Gyeongbokgung",
    "app.categoryLabel": "Kategori",
    "app.descLabel": "Ulasan Anda",
    "app.descPh": "Bagikan pengalaman Anda...",
    "app.addressLabel": "Alamat",
    "app.addressPh": "Cari alamat...",
    "app.searchBtn": "Cari",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@username atau #hashtag",
    "app.authorLabel": "Nama Anda",
    "app.authorPh": "Nama Anda",
    "app.cancelBtn": "Batal",
    "app.submitBtn": "Kirim",
    "app.submitted": "Terima kasih! Tempat Anda akan tampil setelah ditinjau admin.",
    "app.submitError": "Gagal mengirim. Silakan coba lagi.",
    "app.mapError": "Peta tidak dapat dimuat.",

    "auth.signIn": "Masuk",
    "auth.signOut": "Keluar",
    "auth.signInWith": "Masuk dengan Google",
    "auth.welcome": "Selamat datang",

    "bookmark.wantToVisit": "Ingin Dikunjungi",
    "bookmark.interested": "Tertarik",
    "bookmark.remove": "Hapus",
    "bookmark.saved": "Tersimpan!",
    "bookmark.removed": "Dihapus",
    "bookmark.loginRequired": "Masuk untuk menyimpan tempat",
    "bookmark.mySpots": "Tempat Saya",
    "bookmark.noBookmarks": "Belum ada tempat tersimpan",
    "bookmark.wantToVisitEmpty": "Belum ada tempat 'Ingin Dikunjungi'",
    "bookmark.interestedEmpty": "Belum ada tempat 'Tertarik'",

    "planner.title": "Perencana Perjalanan AI",
    "planner.desc": "Rencanakan perjalanan berdasarkan tempat tersimpan",
    "planner.days": "Durasi Perjalanan",
    "planner.daysUnit": "hari",
    "planner.budget": "Anggaran",
    "planner.budgetBudget": "Hemat",
    "planner.budgetModerate": "Sedang",
    "planner.budgetLuxury": "Mewah",
    "planner.style": "Gaya Perjalanan",
    "planner.styleRelaxed": "Santai",
    "planner.styleBalanced": "Seimbang",
    "planner.stylePacked": "Padat",
    "planner.spots": "Tempat yang Dimasukkan",
    "planner.generate": "Buat Rencana",
    "planner.generating": "Membuat rencana perjalanan...",
    "planner.result": "Rencana Perjalanan",
    "planner.retry": "Buat Ulang",
    "planner.close": "Tutup",
    "planner.noSpots": "Simpan tempat ke 'Ingin Dikunjungi' dulu",
    "planner.error": "Gagal membuat rencana. Silakan coba lagi.",
    "planner.rateLimit": "Batas harian tercapai ({limit} rencana/hari). Coba lagi besok!",
    "planner.remaining": "{n} rencana tersisa hari ini",
    "planner.btn": "Rencana Perjalanan",
    "planner.save": "Simpan Rencana",
    "planner.saved": "Rencana tersimpan!",
    "planner.myPlans": "Rencana Saya",
    "planner.compare": "Bandingkan",
    "planner.comparePlans": "Bandingkan Rencana",
    "planner.noSavedPlans": "Belum ada rencana tersimpan",
    "planner.deletePlan": "Hapus",
    "planner.viewPlan": "Lihat",
    "planner.planTitle": "Perjalanan {days} Hari",
    "planner.spots_count": "{n} tempat",
    "planner.savedLocal": "Tersimpan di perangkat ini",
    "planner.selectToCompare": "Pilih 2-3 rencana untuk dibandingkan",
    "planner.back": "Kembali",
    "planner.namePrompt": "Beri nama rencana ini:",
    "planner.share": "Bagikan",
    "planner.shareTitle": "Bagikan rencana ini",
    "planner.copyLink": "Salin Link",
    "planner.sharing": "Membuat link berbagi...",

    "tips.title": "Panduan Wisata Korea",
    "tips.officialInfo": "Informasi resmi dari Korea Tourism Organization",
    "tips.transport": "Transportasi",
    "tips.transportDesc": "Korea memiliki transportasi umum yang sangat baik. Gunakan kartu T-money untuk subway, bus, dan taksi.",
    "tips.subway": "Kereta Bawah Tanah",
    "tips.subwayInfo": "Dasar ₩1.400 (T-money), biaya tambahan berdasarkan jarak",
    "tips.bus": "Bus Kota",
    "tips.busInfo": "₩1.500 (T-money)",
    "tips.taxi": "Taksi",
    "tips.taxiInfo": "Dasar ₩4.800, malam +20%",
    "tips.ktx": "KTX (Kereta Cepat)",
    "tips.ktxInfo": "Seoul↔Busan ₩59.800 · Seoul↔Daejeon ₩23.700",
    "tips.airport": "Airport Express (AREX)",
    "tips.airportInfo": "Bandara Incheon↔Stasiun Seoul ₩9.500 (Express)",
    "tips.bookKorail": "Pesan Tiket KTX / Kereta",
    "tips.bookBus": "Pesan Tiket Bus Ekspres",
    "tips.moreTransport": "Info Transportasi Lengkap",
    "tips.meals": "Harga Makanan (Perkiraan)",
    "tips.budget": "Hemat (~₩10.000)",
    "tips.budgetDesc": "Kimbap, jajanan, minimarket",
    "tips.moderate": "Menengah (₩10.000~30.000)",
    "tips.moderateDesc": "Restoran Korea, kafe, Korean BBQ",
    "tips.luxury": "Mewah (₩30.000+)",
    "tips.luxuryDesc": "Daging hanwoo, fine dining, omakase",
    "tips.useful": "Tips Berguna",
    "tips.tmoney": "Beli kartu T-money (₩4.000) di minimarket untuk subway, bus & taksi",
    "tips.tipping": "Memberi tip tidak umum di Korea",
    "tips.atm": "ATM tersedia di semua minimarket (CU, GS25, 7-Eleven)",
    "tips.emergency": "Darurat: 112 (Polisi), 119 (Pemadam/Ambulans)",
    "tips.hotline": "1330 Korea Travel Hotline — 24 jam, dukungan multibahasa",
    "tips.visitKorea": "Visit Korea — Panduan Wisata Resmi",
    "tips.lastUpdated": "Harga per Jan 2026 · Sumber: Korea Tourism Organization",
    "tips.btn": "Panduan Wisata",
    "tips.taxiGuide": "Panduan Taksi untuk Wisatawan Asing",
    "tips.taxiIntro": "Taksi di Korea aman, bersih, dan terjangkau. Berikut panduan lengkap berdasarkan pengalaman wisatawan.",
    "tips.taxiApp": "Aplikasi yang Direkomendasikan",
    "tips.taxiAppDesc": "K-ride (oleh Kakao, UI 100% bahasa Inggris, kartu kredit internasional) atau TABA (aplikasi taksi resmi Seoul untuk turis asing). Tidak perlu nomor telepon Korea.",
    "tips.taxiHail": "Menghentikan Taksi",
    "tips.taxiHailDesc": "Cari taksi dengan lampu merah '빈차' (kosong). Angkat tangan di pinggir jalan. Tunjukkan tujuan dalam bahasa Korea di ponsel Anda (gunakan Naver Map atau KakaoMap).",
    "tips.taxiTypes": "Jenis Taksi",
    "tips.taxiRegular": "Reguler (oranye/putih/perak) — Dasar ₩4.800",
    "tips.taxiDeluxe": "Deluxe/Mobeom (hitam, garis kuning) — Dasar ₩7.000, tanpa biaya malam",
    "tips.taxiInternational": "Taksi Internasional — Sopir berbahasa Inggris/Mandarin/Jepang",
    "tips.taxiPay": "Pembayaran",
    "tips.taxiPayDesc": "Tunai, kartu kredit (Visa/Mastercard), T-money, KakaoPay, Samsung Pay semua diterima. Tidak perlu tip.",
    "tips.taxiSafety": "Tips Keamanan",
    "tips.taxiSafety1": "Selalu pastikan argo menyala saat naik",
    "tips.taxiSafety2": "Di bandara, gunakan tempat taksi resmi — jangan terima tawaran dari orang yang menghampiri di dalam terminal",
    "tips.taxiSafety3": "Tolak tawaran tarif tetap — argo hampir selalu lebih murah",
    "tips.taxiSafety4": "Taksi resmi memiliki plat kuning (아, 바, 사, 자)",
    "tips.taxiSafety5": "Laporkan masalah: hubungi 1330 (Hotline Wisata, multibahasa)",
    "tips.taxiCost": "Perkiraan Biaya",
    "tips.taxiCostAirport": "Bandara Incheon → Seoul: ₩65.000~80.000 + tol ₩2.000",
    "tips.taxiCostCity": "Dalam Seoul (10 menit): ₩6.000~10.000",
    "tips.taxiCostNight": "Malam (22:00-04:00): +20% biaya tambahan (taksi reguler saja)",
    "tips.taxiDoor": "Pintu TIDAK otomatis — buka dan tutup sendiri (tidak seperti di Jepang)",
    "tips.taxiReviews": "Ulasan Wisatawan",
    "tips.taxiKride": "Unduh K-ride",
    "tips.taxiTaba": "Unduh TABA",

    "footer.text": "© 2026 TravelKo by KoInfo. Temukan Korea bersama.",
    "footer.privacy": "Kebijakan Privasi",
    "footer.terms": "Ketentuan Layanan",
  },

  mn: {
    "common.tagline": "TravelKo",
    "seo.title": "TravelKo - Солонгосыг нээгээрэй | Аялалын хамгийн сайн гарын авлага",
    "seo.description": "Коммунитигээс санал болгосон Солонгосын шилдэг аялалын газруудыг нээгээрэй. Хоол, үзвэр, кафе, байгаль болон бусад.",
    "nav.home": "Нүүр",
    "nav.explore": "Нээх",
    "nav.lang": "한국어",

    "app.title": "Солонгосыг нээгээрэй",
    "app.subtitle": "Коммунитигээс санал болгосон аялалын газрууд",
    "app.searchPh": "Газар хайх...",
    "app.catAll": "Бүгд",
    "app.catFood": "Хоол",
    "app.catAttraction": "Үзмэр газар",
    "app.catCafe": "Кафе",
    "app.catNature": "Байгаль",
    "app.catShopping": "Дэлгүүр",
    "app.catNightlife": "Шөнийн амьдрал",
    "app.catHalal": "Halal Food",
    "app.catMosque": "Mosque",
    "app.catVegetarian": "Цагаан хоол",
    "app.muslimToggle": "Muslim Friendly",
    "app.muslimDesc": "+ Halal restaurants & mosques included",
    "app.viewMap": "Газрын зураг",
    "app.viewList": "Жагсаалт",
    "app.regionAll": "Бүх бүс",
    "app.regionSeoul": "Сөүл",
    "app.regionBusan": "Пусан",
    "app.regionJeju": "Жэжу",
    "app.regionIncheon": "Инчон",
    "app.regionGyeonggi": "Кёнги",
    "app.regionOther": "Бусад",
    "app.featured": "Онцлох",
    "app.rating": "Үнэлгээ",
    "app.views": "Үзсэн",
    "app.noResults": "Газар олдсонгүй. Өөр шүүлтүүр туршаарай.",
    "app.loading": "Ачаалж байна...",
    "app.loadMore": "Дэлгэрэнгүй",
    "app.openNaver": "Naver Map-д нээх",
    "app.openGoogle": "Google Map-д нээх",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Газар хуваалцах",
    "app.submitTitle": "Аялалын газар хуваалцах",
    "app.submitNotice": "Админ зөвшөөрсний дараа нийтлэгдэнэ.",
    "app.placeLabel": "Газрын нэр",
    "app.placePh": "жишээ: Кёнбоккүн ордон",
    "app.categoryLabel": "Ангилал",
    "app.descLabel": "Тойм",
    "app.descPh": "Туршлагаа хуваалцаарай...",
    "app.addressLabel": "Хаяг",
    "app.addressPh": "Хаяг хайх...",
    "app.searchBtn": "Хайх",
    "app.instagramLabel": "Instagram таг",
    "app.instagramPh": "@хэрэглэгч эсвэл #hashtag",
    "app.authorLabel": "Таны нэр",
    "app.authorPh": "Нэр",
    "app.cancelBtn": "Цуцлах",
    "app.submitBtn": "Илгээх",
    "app.submitted": "Баярлалаа! Админ зөвшөөрсний дараа харагдана.",
    "app.submitError": "Илгээхэд алдаа гарлаа. Дахин оролдоно уу.",
    "app.mapError": "Газрын зургийг ачаалж чадсангүй.",

    "auth.signIn": "Нэвтрэх",
    "auth.signOut": "Гарах",
    "auth.signInWith": "Google-ээр нэвтрэх",
    "auth.welcome": "Тавтай морил",

    "bookmark.wantToVisit": "Очих газар",
    "bookmark.interested": "Сонирхолтой",
    "bookmark.remove": "Устгах",
    "bookmark.saved": "Хадгалсан!",
    "bookmark.removed": "Устгагдсан",
    "bookmark.loginRequired": "Газар хадгалахын тулд нэвтэрнэ үү",
    "bookmark.mySpots": "Миний газрууд",
    "bookmark.noBookmarks": "Хадгалсан газар байхгүй байна",
    "bookmark.wantToVisitEmpty": "'Очих газар' байхгүй байна",
    "bookmark.interestedEmpty": "'Сонирхолтой' газар байхгүй байна",

    "planner.title": "AI Аялалын Төлөвлөгч",
    "planner.desc": "Хадгалсан газруудын дагуу аялалаа төлөвлөөрэй",
    "planner.days": "Аялалын хугацаа",
    "planner.daysUnit": "өдөр",
    "planner.budget": "Төсөв",
    "planner.budgetBudget": "Хямд",
    "planner.budgetModerate": "Дунд зэрэг",
    "planner.budgetLuxury": "Тансаг",
    "planner.style": "Аялалын хэв маяг",
    "planner.styleRelaxed": "Чөлөөтэй",
    "planner.styleBalanced": "Тэнцвэртэй",
    "planner.stylePacked": "Нягт",
    "planner.spots": "Оруулах газрууд",
    "planner.generate": "Төлөвлөгөө үүсгэх",
    "planner.generating": "Аялалын төлөвлөгөө үүсгэж байна...",
    "planner.result": "Аялалын төлөвлөгөө",
    "planner.retry": "Дахин үүсгэх",
    "planner.close": "Хаах",
    "planner.noSpots": "Эхлээд 'Очих газар'-т газар хадгалаарай",
    "planner.error": "Төлөвлөгөө үүсгэж чадсангүй. Дахин оролдоно уу.",
    "planner.rateLimit": "Өдрийн хязгаарт хүрсэн ({limit} төлөвлөгөө/өдөр). Маргааш дахин оролдоно уу!",
    "planner.remaining": "Өнөөдөр {n} төлөвлөгөө үлдсэн",
    "planner.btn": "Аялал төлөвлөх",
    "planner.save": "Төлөвлөгөө хадгалах",
    "planner.saved": "Төлөвлөгөө хадгалагдлаа!",
    "planner.myPlans": "Миний төлөвлөгөө",
    "planner.compare": "Харьцуулах",
    "planner.comparePlans": "Төлөвлөгөө харьцуулах",
    "planner.noSavedPlans": "Хадгалсан төлөвлөгөө байхгүй",
    "planner.deletePlan": "Устгах",
    "planner.viewPlan": "Харах",
    "planner.planTitle": "{days} өдрийн аялал",
    "planner.spots_count": "{n} газар",
    "planner.savedLocal": "Энэ төхөөрөмж дээр хадгалсан",
    "planner.selectToCompare": "Харьцуулах 2-3 төлөвлөгөө сонгоно уу",
    "planner.back": "Буцах",
    "planner.namePrompt": "Төлөвлөгөөний нэр:",
    "planner.share": "Хуваалцах",
    "planner.shareTitle": "Энэ төлөвлөгөөг хуваалцах",
    "planner.copyLink": "Линк хуулах",
    "planner.sharing": "Хуваалцах линк үүсгэж байна...",

    "tips.title": "Солонгос аялалын гарын авлага",
    "tips.officialInfo": "Солонгосын Аялал Жуулчлалын Байгууллагын албан ёсны мэдээлэл",
    "tips.transport": "Тээвэр",
    "tips.transportDesc": "Солонгост нийтийн тээвэр маш сайн хөгжсөн. T-money картаар метро, автобус, таксинд ашиглана.",
    "tips.subway": "Метро",
    "tips.subwayInfo": "Үндсэн ₩1,400 (T-money), зайнаас хамаарсан нэмэлт",
    "tips.bus": "Хотын автобус",
    "tips.busInfo": "₩1,500 (T-money)",
    "tips.taxi": "Такси",
    "tips.taxiInfo": "Үндсэн ₩4,800, шөнийн +20%",
    "tips.ktx": "KTX (Өндөр хурдны галт тэрэг)",
    "tips.ktxInfo": "Seoul↔Busan ₩59,800 · Seoul↔Daejeon ₩23,700",
    "tips.airport": "Нисэх буудлын экспресс (AREX)",
    "tips.airportInfo": "Инчон нисэх буудал↔Сөүл вокзал ₩9,500 (Express)",
    "tips.bookKorail": "KTX / Галт тэрэгний тасалбар захиалах",
    "tips.bookBus": "Экспресс автобусны тасалбар захиалах",
    "tips.moreTransport": "Тээврийн дэлгэрэнгүй мэдээлэл",
    "tips.meals": "Хоолны үнэ (Ойролцоо)",
    "tips.budget": "Хямд (~₩10,000)",
    "tips.budgetDesc": "Кимбаб, гудамжны хоол, дэлгүүр",
    "tips.moderate": "Дунд (₩10,000~30,000)",
    "tips.moderateDesc": "Солонгос ресторан, кафе, Korean BBQ",
    "tips.luxury": "Тансаг (₩30,000+)",
    "tips.luxuryDesc": "Ханү үхрийн мах, fine dining, omakase",
    "tips.useful": "Хэрэгтэй зөвлөмж",
    "tips.tmoney": "Дэлгүүрээс T-money карт (₩4,000) авч метро, автобус, таксинд хэрэглэнэ",
    "tips.tipping": "Солонгост tip өгөх заншил байхгүй",
    "tips.atm": "Бүх дэлгүүрт (CU, GS25, 7-Eleven) ATM байдаг",
    "tips.emergency": "Яаралтай: 112 (Цагдаа), 119 (Гал/Түргэн)",
    "tips.hotline": "1330 Аялал жуулчлалын лавлах — 24 цаг, олон хэлээр",
    "tips.visitKorea": "Visit Korea — Албан ёсны аялалын гарын авлага",
    "tips.lastUpdated": "2026 оны 1-р сарын байдлаар · Эх сурвалж: Korea Tourism Organization",
    "tips.btn": "Аялалын гарын авлага",
    "tips.taxiGuide": "Гадаадын иргэдэд зориулсан такси гарын авлага",
    "tips.taxiIntro": "Солонгосын такси аюулгүй, цэвэрхэн, хямд. Жинхэнэ аялагчдын туршлага дээр тулгуурласан гарын авлага.",
    "tips.taxiApp": "Санал болгох аппликейшн",
    "tips.taxiAppDesc": "K-ride (Kakao, 100% англи хэлээр, олон улсын карт) эсвэл TABA (Сөүлийн албан ёсны гадаадын жуулчдын такси апп). Солонгос утасны дугаар шаардахгүй.",
    "tips.taxiHail": "Такси зогсоох",
    "tips.taxiHailDesc": "Улаан '빈차' (сул) гэрэлтэй таксийг хайна уу. Замын хажууд гараа өргө. Очих газраа Naver Map эсвэл KakaoMap-аас солонгос хэлээр харуулна уу.",
    "tips.taxiTypes": "Таксийн төрөл",
    "tips.taxiRegular": "Энгийн (улбар шар/цагаан/мөнгөлөг) — Үндсэн ₩4,800",
    "tips.taxiDeluxe": "Тансаг/Мобом (хар, шар зурвас) — Үндсэн ₩7,000, шөнийн нэмэлтгүй",
    "tips.taxiInternational": "Олон улсын такси — Англи/Хятад/Япон хэлтэй жолооч",
    "tips.taxiPay": "Төлбөр",
    "tips.taxiPayDesc": "Бэлэн мөнгө, карт (Visa/Mastercard), T-money, KakaoPay, Samsung Pay бүгд хүлээн авна. Tip өгөх шаардлагагүй.",
    "tips.taxiSafety": "Аюулгүй байдлын зөвлөмж",
    "tips.taxiSafety1": "Суусан даруйд тоолуур ажиллаж буйг шалгаарай",
    "tips.taxiSafety2": "Нисэх буудалд албан ёсны такси зогсоол ашиглана уу",
    "tips.taxiSafety3": "Тогтмол үнийн саналаас татгалзаарай — тоолуур бараг үргэлж хямд",
    "tips.taxiSafety4": "Албан ёсны такси шар дугаарын хавтантай (아, 바, 사, 자)",
    "tips.taxiSafety5": "Асуудал гарвал: 1330 руу залгана уу (Аялал жуулчлалын лавлах)",
    "tips.taxiCost": "Ойролцоо зардал",
    "tips.taxiCostAirport": "Инчон нисэх буудал → Сөүл: ₩65,000~80,000 + зам ₩2,000",
    "tips.taxiCostCity": "Сөүл дотор (10 мин): ₩6,000~10,000",
    "tips.taxiCostNight": "Шөнийн (22:00-04:00): +20% нэмэлт (энгийн такси)",
    "tips.taxiDoor": "Хаалга автомат БИШ — өөрөө нээж хаана уу (Японтой адилгүй)",
    "tips.taxiReviews": "Жинхэнэ аялагчдын сэтгэгдэл",
    "tips.taxiKride": "K-ride татах",
    "tips.taxiTaba": "TABA татах",

    "footer.text": "© 2026 TravelKo by KoInfo. Солонгосыг хамтдаа нээцгээе.",
    "footer.privacy": "Нууцлалын бодлого",
    "footer.terms": "Үйлчилгээний нөхцөл",
  },

  ms: {
    "common.tagline": "TravelKo",
    "seo.title": "TravelKo - Temui Korea | Panduan Pelancongan Terbaik",
    "seo.description": "Temui tempat pelancongan terbaik di Korea yang dicadangkan oleh komuniti. Makanan, tarikan, kafe, alam semula jadi dan banyak lagi.",
    "nav.home": "Laman Utama",
    "nav.explore": "Terokai",
    "nav.lang": "한국어",

    "app.title": "Temui Korea",
    "app.subtitle": "Tempat pelancongan cadangan komuniti",
    "app.searchPh": "Cari tempat...",
    "app.catAll": "Semua",
    "app.catFood": "Makanan",
    "app.catAttraction": "Tarikan",
    "app.catCafe": "Kafe",
    "app.catNature": "Alam Semula Jadi",
    "app.catShopping": "Beli-belah",
    "app.catNightlife": "Kehidupan Malam",
    "app.catHalal": "Makanan Halal",
    "app.catMosque": "Masjid",
    "app.catVegetarian": "Vegetarian",
    "app.muslimToggle": "Mesra Muslim",
    "app.muslimDesc": "+ Restoran halal & masjid disertakan",
    "app.viewMap": "Peta",
    "app.viewList": "Senarai",
    "app.regionAll": "Semua Wilayah",
    "app.regionSeoul": "Seoul",
    "app.regionBusan": "Busan",
    "app.regionJeju": "Jeju",
    "app.regionIncheon": "Incheon",
    "app.regionGyeonggi": "Gyeonggi",
    "app.regionOther": "Lain-lain",
    "app.featured": "Pilihan",
    "app.rating": "Penilaian",
    "app.views": "Tontonan",
    "app.noResults": "Tiada tempat ditemui. Cuba penapis lain.",
    "app.loading": "Memuatkan...",
    "app.loadMore": "Muat Lagi",
    "app.openNaver": "Buka di Naver Map",
    "app.openGoogle": "Buka di Google Map",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Kongsi Tempat",
    "app.submitTitle": "Kongsi Tempat Pelancongan",
    "app.submitNotice": "Akan dipaparkan selepas semakan admin.",
    "app.placeLabel": "Nama Tempat",
    "app.placePh": "cth: Istana Gyeongbokgung",
    "app.categoryLabel": "Kategori",
    "app.descLabel": "Ulasan Anda",
    "app.descPh": "Kongsi pengalaman anda...",
    "app.addressLabel": "Alamat",
    "app.addressPh": "Cari alamat...",
    "app.searchBtn": "Cari",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@pengguna atau #hashtag",
    "app.authorLabel": "Nama Anda",
    "app.authorPh": "Nama anda",
    "app.cancelBtn": "Batal",
    "app.submitBtn": "Hantar",
    "app.submitted": "Terima kasih! Tempat anda akan dipaparkan selepas semakan admin.",
    "app.submitError": "Gagal menghantar. Sila cuba lagi.",
    "app.mapError": "Peta tidak dapat dimuatkan.",

    "auth.signIn": "Log Masuk",
    "auth.signOut": "Log Keluar",
    "auth.signInWith": "Log masuk dengan Google",
    "auth.welcome": "Selamat datang",

    "bookmark.wantToVisit": "Ingin Dikunjungi",
    "bookmark.interested": "Berminat",
    "bookmark.remove": "Buang",
    "bookmark.saved": "Disimpan!",
    "bookmark.removed": "Dibuang",
    "bookmark.loginRequired": "Log masuk untuk menyimpan tempat",
    "bookmark.mySpots": "Tempat Saya",
    "bookmark.noBookmarks": "Tiada tempat tersimpan lagi",
    "bookmark.wantToVisitEmpty": "Tiada tempat 'Ingin Dikunjungi' lagi",
    "bookmark.interestedEmpty": "Tiada tempat 'Berminat' lagi",

    "planner.title": "Perancang Perjalanan AI",
    "planner.desc": "Rancang perjalanan berdasarkan tempat tersimpan",
    "planner.days": "Tempoh Perjalanan",
    "planner.daysUnit": "hari",
    "planner.budget": "Bajet",
    "planner.budgetBudget": "Jimat",
    "planner.budgetModerate": "Sederhana",
    "planner.budgetLuxury": "Mewah",
    "planner.style": "Gaya Perjalanan",
    "planner.styleRelaxed": "Santai",
    "planner.styleBalanced": "Seimbang",
    "planner.stylePacked": "Padat",
    "planner.spots": "Tempat Dimasukkan",
    "planner.generate": "Buat Rancangan",
    "planner.generating": "Mencipta rancangan perjalanan...",
    "planner.result": "Rancangan Perjalanan",
    "planner.retry": "Buat Semula",
    "planner.close": "Tutup",
    "planner.noSpots": "Simpan tempat ke 'Ingin Dikunjungi' dahulu",
    "planner.error": "Gagal mencipta rancangan. Sila cuba lagi.",
    "planner.rateLimit": "Had harian dicapai ({limit} rancangan/hari). Cuba lagi esok!",
    "planner.remaining": "{n} rancangan baki hari ini",
    "planner.btn": "Rancang Perjalanan",
    "planner.save": "Simpan Rancangan",
    "planner.saved": "Rancangan disimpan!",
    "planner.myPlans": "Rancangan Saya",
    "planner.compare": "Bandingkan",
    "planner.comparePlans": "Bandingkan Rancangan",
    "planner.noSavedPlans": "Tiada rancangan tersimpan",
    "planner.deletePlan": "Padam",
    "planner.viewPlan": "Lihat",
    "planner.planTitle": "Perjalanan {days} Hari",
    "planner.spots_count": "{n} tempat",
    "planner.savedLocal": "Disimpan di peranti ini",
    "planner.selectToCompare": "Pilih 2-3 rancangan untuk dibandingkan",
    "planner.back": "Kembali",
    "planner.namePrompt": "Namakan rancangan ini:",
    "planner.share": "Kongsi",
    "planner.shareTitle": "Kongsi rancangan ini",
    "planner.copyLink": "Salin Pautan",
    "planner.sharing": "Mencipta pautan kongsi...",

    "tips.title": "Panduan Pelancongan Korea",
    "tips.officialInfo": "Maklumat rasmi dari Korea Tourism Organization",
    "tips.transport": "Pengangkutan",
    "tips.transportDesc": "Korea mempunyai sistem pengangkutan awam yang cemerlang. Gunakan kad T-money untuk subway, bas dan teksi.",
    "tips.subway": "Kereta Api Bawah Tanah",
    "tips.subwayInfo": "Asas ₩1,400 (T-money), caj tambahan berdasarkan jarak",
    "tips.bus": "Bas Bandar",
    "tips.busInfo": "₩1,500 (T-money)",
    "tips.taxi": "Teksi",
    "tips.taxiInfo": "Asas ₩4,800, malam +20%",
    "tips.ktx": "KTX (Kereta Laju)",
    "tips.ktxInfo": "Seoul↔Busan ₩59,800 · Seoul↔Daejeon ₩23,700",
    "tips.airport": "Airport Express (AREX)",
    "tips.airportInfo": "Lapangan Terbang Incheon↔Stesen Seoul ₩9,500 (Express)",
    "tips.bookKorail": "Tempah Tiket KTX / Kereta Api",
    "tips.bookBus": "Tempah Tiket Bas Ekspres",
    "tips.moreTransport": "Maklumat Pengangkutan Lanjut",
    "tips.meals": "Harga Makanan (Anggaran)",
    "tips.budget": "Jimat (~₩10,000)",
    "tips.budgetDesc": "Kimbap, makanan jalanan, kedai serbaneka",
    "tips.moderate": "Sederhana (₩10,000~30,000)",
    "tips.moderateDesc": "Restoran Korea, kafe, Korean BBQ",
    "tips.luxury": "Mewah (₩30,000+)",
    "tips.luxuryDesc": "Daging hanwoo, fine dining, omakase",
    "tips.useful": "Tips Berguna",
    "tips.tmoney": "Beli kad T-money (₩4,000) di kedai serbaneka untuk subway, bas & teksi",
    "tips.tipping": "Memberi tip tidak diamalkan di Korea",
    "tips.atm": "ATM tersedia di semua kedai serbaneka (CU, GS25, 7-Eleven)",
    "tips.emergency": "Kecemasan: 112 (Polis), 119 (Bomba/Ambulans)",
    "tips.hotline": "1330 Korea Travel Hotline — 24 jam, sokongan pelbagai bahasa",
    "tips.visitKorea": "Visit Korea — Panduan Pelancongan Rasmi",
    "tips.lastUpdated": "Harga setakat Jan 2026 · Sumber: Korea Tourism Organization",
    "tips.btn": "Panduan Pelancongan",
    "tips.taxiGuide": "Panduan Teksi untuk Pelancong Asing",
    "tips.taxiIntro": "Teksi di Korea selamat, bersih dan berpatutan. Berikut panduan lengkap berdasarkan pengalaman pelancong sebenar.",
    "tips.taxiApp": "Aplikasi Disyorkan",
    "tips.taxiAppDesc": "K-ride (oleh Kakao, UI bahasa Inggeris, kad kredit antarabangsa) atau TABA (aplikasi teksi rasmi Seoul untuk pelancong asing). Tidak perlu nombor telefon Korea.",
    "tips.taxiHail": "Menghentikan Teksi",
    "tips.taxiHailDesc": "Cari teksi dengan lampu merah '빈차' (kosong). Angkat tangan di tepi jalan. Tunjukkan destinasi dalam bahasa Korea di telefon (guna Naver Map atau KakaoMap).",
    "tips.taxiTypes": "Jenis Teksi",
    "tips.taxiRegular": "Biasa (oren/putih/perak) — Asas ₩4,800",
    "tips.taxiDeluxe": "Deluxe/Mobeom (hitam, jalur kuning) — Asas ₩7,000, tiada surcaj malam",
    "tips.taxiInternational": "Teksi Antarabangsa — Pemandu berbahasa Inggeris/Mandarin/Jepun",
    "tips.taxiPay": "Pembayaran",
    "tips.taxiPayDesc": "Tunai, kad kredit (Visa/Mastercard), T-money, KakaoPay, Samsung Pay semua diterima. Tidak perlu tip.",
    "tips.taxiSafety": "Tips Keselamatan",
    "tips.taxiSafety1": "Sentiasa pastikan meter berjalan semasa naik",
    "tips.taxiSafety2": "Di lapangan terbang, guna tempat teksi rasmi — jangan terima tawaran dari orang dalam terminal",
    "tips.taxiSafety3": "Tolak tawaran harga tetap — meter hampir selalu lebih murah",
    "tips.taxiSafety4": "Teksi rasmi mempunyai plat kuning (아, 바, 사, 자)",
    "tips.taxiSafety5": "Laporkan masalah: hubungi 1330 (Hotline Pelancongan, pelbagai bahasa)",
    "tips.taxiCost": "Anggaran Kos",
    "tips.taxiCostAirport": "Lapangan Terbang Incheon → Seoul: ₩65,000~80,000 + tol ₩2,000",
    "tips.taxiCostCity": "Dalam Seoul (10 minit): ₩6,000~10,000",
    "tips.taxiCostNight": "Malam (22:00-04:00): +20% surcaj (teksi biasa sahaja)",
    "tips.taxiDoor": "Pintu TIDAK automatik — buka dan tutup sendiri (tidak seperti Jepun)",
    "tips.taxiReviews": "Ulasan Pelancong Sebenar",
    "tips.taxiKride": "Muat Turun K-ride",
    "tips.taxiTaba": "Muat Turun TABA",

    "footer.text": "© 2026 TravelKo by KoInfo. Temui Korea bersama.",
    "footer.privacy": "Dasar Privasi",
    "footer.terms": "Terma Perkhidmatan",
  },

  vi: {
    "common.tagline": "TravelKo",
    "seo.title": "TravelKo - Khám phá Hàn Quốc | Hướng dẫn du lịch tốt nhất",
    "seo.description": "Khám phá những điểm du lịch tốt nhất tại Hàn Quốc được cộng đồng đề xuất. Ẩm thực, điểm tham quan, quán cà phê, thiên nhiên và nhiều hơn nữa.",
    "nav.home": "Trang ch\u1ee7",
    "nav.explore": "Kh\u00e1m ph\u00e1",
    "nav.lang": "\ud55c\uad6d\uc5b4",

    "app.title": "Kh\u00e1m ph\u00e1 H\u00e0n Qu\u1ed1c",
    "app.subtitle": "\u0110i\u1ec3m du l\u1ecbch \u0111\u01b0\u1ee3c c\u1ed9ng \u0111\u1ed3ng \u0111\u1ec1 xu\u1ea5t",
    "app.searchPh": "T\u00ecm \u0111\u1ecba \u0111i\u1ec3m...",
    "app.catAll": "T\u1ea5t c\u1ea3",
    "app.catFood": "\u1ea8m th\u1ef1c",
    "app.catAttraction": "\u0110i\u1ec3m tham quan",
    "app.catCafe": "C\u00e0 ph\u00ea",
    "app.catNature": "Thi\u00ean nhi\u00ean",
    "app.catShopping": "Mua s\u1eafm",
    "app.catNightlife": "Cu\u1ed9c s\u1ed1ng v\u1ec1 \u0111\u00eam",
    "app.catHalal": "Halal Food",
    "app.catMosque": "Mosque",
    "app.catVegetarian": "Chay",
    "app.muslimToggle": "Muslim Friendly",
    "app.muslimDesc": "+ Bao g\u1ed3m nh\u00e0 h\u00e0ng halal & nh\u00e0 th\u1edd",
    "app.viewMap": "B\u1ea3n \u0111\u1ed3",
    "app.viewList": "Danh s\u00e1ch",
    "app.regionAll": "T\u1ea5t c\u1ea3 khu v\u1ef1c",
    "app.regionSeoul": "Seoul",
    "app.regionBusan": "Busan",
    "app.regionJeju": "Jeju",
    "app.regionIncheon": "Incheon",
    "app.regionGyeonggi": "Gyeonggi",
    "app.regionOther": "Kh\u00e1c",
    "app.featured": "N\u1ed5i b\u1eadt",
    "app.rating": "\u0110\u00e1nh gi\u00e1",
    "app.views": "L\u01b0\u1ee3t xem",
    "app.noResults": "Kh\u00f4ng t\u00ecm th\u1ea5y \u0111\u1ecba \u0111i\u1ec3m. Th\u1eed b\u1ed9 l\u1ecdc kh\u00e1c.",
    "app.loading": "\u0110ang t\u1ea3i...",
    "app.loadMore": "Xem th\u00eam",
    "app.openNaver": "M\u1edf trong Naver Map",
    "app.openGoogle": "M\u1edf trong Google Map",
    "app.mapNaver": "Naver Map",
    "app.mapGoogle": "Google Map",
    "app.shareSpot": "Chia s\u1ebb \u0111\u1ecba \u0111i\u1ec3m",
    "app.submitTitle": "Chia s\u1ebb \u0111\u1ecba \u0111i\u1ec3m du l\u1ecbch",
    "app.submitNotice": "S\u1ebd hi\u1ec3n th\u1ecb sau khi qu\u1ea3n tr\u1ecb vi\u00ean duy\u1ec7t.",
    "app.placeLabel": "T\u00ean \u0111\u1ecba \u0111i\u1ec3m",
    "app.placePh": "v\u00ed d\u1ee5: C\u00f4ng Gyeongbokgung",
    "app.categoryLabel": "Danh m\u1ee5c",
    "app.descLabel": "\u0110\u00e1nh gi\u00e1 c\u1ee7a b\u1ea1n",
    "app.descPh": "Chia s\u1ebb tr\u1ea3i nghi\u1ec7m c\u1ee7a b\u1ea1n...",
    "app.addressLabel": "\u0110\u1ecba ch\u1ec9",
    "app.addressPh": "T\u00ecm \u0111\u1ecba ch\u1ec9...",
    "app.searchBtn": "T\u00ecm",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@t\u00e0i kho\u1ea3n ho\u1eb7c #hashtag",
    "app.authorLabel": "T\u00ean c\u1ee7a b\u1ea1n",
    "app.authorPh": "T\u00ean c\u1ee7a b\u1ea1n",
    "app.cancelBtn": "H\u1ee7y",
    "app.submitBtn": "G\u1eedi",
    "app.submitted": "C\u1ea3m \u01a1n! \u0110\u1ecba \u0111i\u1ec3m s\u1ebd hi\u1ec3n th\u1ecb sau khi \u0111\u01b0\u1ee3c duy\u1ec7t.",
    "app.submitError": "G\u1eedi th\u1ea5t b\u1ea1i. Vui l\u00f2ng th\u1eed l\u1ea1i.",
    "app.mapError": "Kh\u00f4ng th\u1ec3 t\u1ea3i b\u1ea3n \u0111\u1ed3.",

    "auth.signIn": "\u0110\u0103ng nh\u1eadp",
    "auth.signOut": "\u0110\u0103ng xu\u1ea5t",
    "auth.signInWith": "\u0110\u0103ng nh\u1eadp b\u1eb1ng Google",
    "auth.welcome": "Ch\u00e0o m\u1eebng",

    "bookmark.wantToVisit": "Mu\u1ed1n \u0111\u1ebfn",
    "bookmark.interested": "Quan t\u00e2m",
    "bookmark.remove": "X\u00f3a",
    "bookmark.saved": "\u0110\u00e3 l\u01b0u!",
    "bookmark.removed": "\u0110\u00e3 x\u00f3a",
    "bookmark.loginRequired": "\u0110\u0103ng nh\u1eadp \u0111\u1ec3 l\u01b0u \u0111\u1ecba \u0111i\u1ec3m",
    "bookmark.mySpots": "\u0110\u1ecba \u0111i\u1ec3m c\u1ee7a t\u00f4i",
    "bookmark.noBookmarks": "Ch\u01b0a c\u00f3 \u0111\u1ecba \u0111i\u1ec3m n\u00e0o \u0111\u01b0\u1ee3c l\u01b0u",
    "bookmark.wantToVisitEmpty": "Ch\u01b0a c\u00f3 \u0111\u1ecba \u0111i\u1ec3m 'Mu\u1ed1n \u0111\u1ebfn'",
    "bookmark.interestedEmpty": "Ch\u01b0a c\u00f3 \u0111\u1ecba \u0111i\u1ec3m 'Quan t\u00e2m'",

    "planner.title": "AI L\u1eadp K\u1ebf Ho\u1ea1ch Du L\u1ecbch",
    "planner.desc": "L\u1eadp k\u1ebf ho\u1ea1ch d\u1ef1a tr\u00ean \u0111\u1ecba \u0111i\u1ec3m \u0111\u00e3 l\u01b0u",
    "planner.days": "Th\u1eddi gian chuy\u1ebfn \u0111i",
    "planner.daysUnit": "ng\u00e0y",
    "planner.budget": "Ng\u00e2n s\u00e1ch",
    "planner.budgetBudget": "Ti\u1ebft ki\u1ec7m",
    "planner.budgetModerate": "V\u1eeba ph\u1ea3i",
    "planner.budgetLuxury": "Sang tr\u1ecdng",
    "planner.style": "Phong c\u00e1ch du l\u1ecbch",
    "planner.styleRelaxed": "Th\u01b0 th\u00e1",
    "planner.styleBalanced": "C\u00e2n b\u1eb1ng",
    "planner.stylePacked": "D\u00e0y \u0111\u1eb7c",
    "planner.spots": "\u0110\u1ecba \u0111i\u1ec3m bao g\u1ed3m",
    "planner.generate": "T\u1ea1o k\u1ebf ho\u1ea1ch",
    "planner.generating": "\u0110ang t\u1ea1o k\u1ebf ho\u1ea1ch du l\u1ecbch...",
    "planner.result": "K\u1ebf ho\u1ea1ch du l\u1ecbch",
    "planner.retry": "T\u1ea1o l\u1ea1i",
    "planner.close": "\u0110\u00f3ng",
    "planner.noSpots": "H\u00e3y l\u01b0u \u0111\u1ecba \u0111i\u1ec3m v\u00e0o 'Mu\u1ed1n \u0111\u1ebfn' tr\u01b0\u1edbc",
    "planner.error": "T\u1ea1o k\u1ebf ho\u1ea1ch th\u1ea5t b\u1ea1i. Vui l\u00f2ng th\u1eed l\u1ea1i.",
    "planner.rateLimit": "\u0110\u00e3 \u0111\u1ea1t gi\u1edbi h\u1ea1n h\u00e0ng ng\u00e0y ({limit} k\u1ebf ho\u1ea1ch/ng\u00e0y). H\u00e3y th\u1eed l\u1ea1i v\u00e0o ng\u00e0y mai!",
    "planner.remaining": "C\u00f2n l\u1ea1i {n} k\u1ebf ho\u1ea1ch h\u00f4m nay",
    "planner.btn": "L\u1eadp k\u1ebf ho\u1ea1ch",
    "planner.save": "L\u01b0u k\u1ebf ho\u1ea1ch",
    "planner.saved": "K\u1ebf ho\u1ea1ch \u0111\u00e3 l\u01b0u!",
    "planner.myPlans": "K\u1ebf ho\u1ea1ch c\u1ee7a t\u00f4i",
    "planner.compare": "So s\u00e1nh",
    "planner.comparePlans": "So s\u00e1nh k\u1ebf ho\u1ea1ch",
    "planner.noSavedPlans": "Ch\u01b0a c\u00f3 k\u1ebf ho\u1ea1ch n\u00e0o",
    "planner.deletePlan": "X\u00f3a",
    "planner.viewPlan": "Xem",
    "planner.planTitle": "Chuy\u1ebfn {days} ng\u00e0y",
    "planner.spots_count": "{n} \u0111i\u1ec3m",
    "planner.savedLocal": "\u0110\u00e3 l\u01b0u tr\u00ean thi\u1ebft b\u1ecb n\u00e0y",
    "planner.selectToCompare": "Ch\u1ecdn 2-3 k\u1ebf ho\u1ea1ch \u0111\u1ec3 so s\u00e1nh",
    "planner.back": "Quay l\u1ea1i",
    "planner.namePrompt": "\u0110\u1eb7t t\u00ean k\u1ebf ho\u1ea1ch:",
    "planner.share": "Chia s\u1ebb",
    "planner.shareTitle": "Chia s\u1ebb k\u1ebf ho\u1ea1ch n\u00e0y",
    "planner.copyLink": "Sao ch\u00e9p li\u00ean k\u1ebft",
    "planner.sharing": "\u0110ang t\u1ea1o li\u00ean k\u1ebft chia s\u1ebb...",

    "tips.title": "H\u01b0\u1edbng d\u1eabn du l\u1ecbch H\u00e0n Qu\u1ed1c",
    "tips.officialInfo": "Th\u00f4ng tin ch\u00ednh th\u1ee9c t\u1eeb T\u1ed5 ch\u1ee9c Du l\u1ecbch H\u00e0n Qu\u1ed1c",
    "tips.transport": "Ph\u01b0\u01a1ng ti\u1ec7n giao th\u00f4ng",
    "tips.transportDesc": "H\u00e0n Qu\u1ed1c c\u00f3 h\u1ec7 th\u1ed1ng giao th\u00f4ng c\u00f4ng c\u1ed9ng tuy\u1ec7t v\u1eddi. D\u00f9ng th\u1ebb T-money cho subway, bus v\u00e0 taxi.",
    "tips.subway": "T\u00e0u \u0111i\u1ec7n ng\u1ea7m",
    "tips.subwayInfo": "C\u01a1 b\u1ea3n \u20a91.400 (T-money), ph\u1ee5 thu theo kho\u1ea3ng c\u00e1ch",
    "tips.bus": "Xe bu\u00fdt th\u00e0nh ph\u1ed1",
    "tips.busInfo": "\u20a91.500 (T-money)",
    "tips.taxi": "Taxi",
    "tips.taxiInfo": "C\u01a1 b\u1ea3n \u20a94.800, \u0111\u00eam khuya +20%",
    "tips.ktx": "KTX (T\u00e0u cao t\u1ed1c)",
    "tips.ktxInfo": "Seoul\u2194Busan \u20a959.800 \u00b7 Seoul\u2194Daejeon \u20a923.700",
    "tips.airport": "Airport Express (AREX)",
    "tips.airportInfo": "S\u00e2n bay Incheon\u2194Ga Seoul \u20a99.500 (Express)",
    "tips.bookKorail": "\u0110\u1eb7t v\u00e9 KTX / T\u00e0u h\u1ecfa",
    "tips.bookBus": "\u0110\u1eb7t v\u00e9 xe bu\u00fdt cao t\u1ed1c",
    "tips.moreTransport": "Th\u00f4ng tin giao th\u00f4ng chi ti\u1ebft",
    "tips.meals": "Gi\u00e1 b\u1eefa \u0103n (\u01af\u1edbc t\u00ednh)",
    "tips.budget": "Ti\u1ebft ki\u1ec7m (~\u20a910.000)",
    "tips.budgetDesc": "Kimbap, \u0111\u1ed3 \u0103n v\u1eb7t, c\u1eeda h\u00e0ng ti\u1ec7n l\u1ee3i",
    "tips.moderate": "V\u1eeba ph\u1ea3i (\u20a910.000~30.000)",
    "tips.moderateDesc": "Nh\u00e0 h\u00e0ng H\u00e0n, c\u00e0 ph\u00ea, Korean BBQ",
    "tips.luxury": "Sang tr\u1ecdng (\u20a930.000+)",
    "tips.luxuryDesc": "Th\u1ecbt b\u00f2 hanwoo, fine dining, omakase",
    "tips.useful": "M\u1eb9o h\u1eefu \u00edch",
    "tips.tmoney": "Mua th\u1ebb T-money (\u20a94.000) t\u1ea1i c\u1eeda h\u00e0ng ti\u1ec7n l\u1ee3i cho subway, bus & taxi",
    "tips.tipping": "Kh\u00f4ng c\u00f3 v\u0103n h\u00f3a tip \u1edf H\u00e0n Qu\u1ed1c",
    "tips.atm": "ATM c\u00f3 t\u1ea1i t\u1ea5t c\u1ea3 c\u1eeda h\u00e0ng ti\u1ec7n l\u1ee3i (CU, GS25, 7-Eleven)",
    "tips.emergency": "Kh\u1ea9n c\u1ea5p: 112 (C\u1ea3nh s\u00e1t), 119 (PCCC/C\u1ea5p c\u1ee9u)",
    "tips.hotline": "1330 Korea Travel Hotline \u2014 24/7, h\u1ed7 tr\u1ee3 \u0111a ng\u00f4n ng\u1eef",
    "tips.visitKorea": "Visit Korea \u2014 H\u01b0\u1edbng d\u1eabn du l\u1ecbch ch\u00ednh th\u1ee9c",
    "tips.lastUpdated": "Gi\u00e1 t\u00ednh \u0111\u1ebfn Th\u00e1ng 1/2026 \u00b7 Ngu\u1ed3n: Korea Tourism Organization",
    "tips.btn": "H\u01b0\u1edbng d\u1eabn du l\u1ecbch",
    "tips.taxiGuide": "H\u01b0\u1edbng d\u1eabn taxi cho ng\u01b0\u1eddi n\u01b0\u1edbc ngo\u00e0i",
    "tips.taxiIntro": "Taxi \u1edf H\u00e0n Qu\u1ed1c an to\u00e0n, s\u1ea1ch s\u1ebd v\u00e0 gi\u00e1 c\u1ea3 h\u1ee3p l\u00fd. D\u01b0\u1edbi \u0111\u00e2y l\u00e0 h\u01b0\u1edbng d\u1eabn d\u1ef1a tr\u00ean tr\u1ea3i nghi\u1ec7m th\u1ef1c t\u1ebf c\u1ee7a du kh\u00e1ch.",
    "tips.taxiApp": "\u1ee8ng d\u1ee5ng khuy\u00ean d\u00f9ng",
    "tips.taxiAppDesc": "K-ride (Kakao, giao di\u1ec7n ti\u1ebfng Anh, th\u1ebb qu\u1ed1c t\u1ebf) ho\u1eb7c TABA (app taxi ch\u00ednh th\u1ee9c Seoul cho du kh\u00e1ch). Kh\u00f4ng c\u1ea7n s\u1ed1 \u0111i\u1ec7n tho\u1ea1i H\u00e0n Qu\u1ed1c.",
    "tips.taxiHail": "B\u1eaft taxi",
    "tips.taxiHailDesc": "T\u00ecm taxi c\u00f3 \u0111\u00e8n \u0111\u1ecf '\ube48\ucc28' (tr\u1ed1ng). Gi\u01a1 tay \u1edf l\u1ec1 \u0111\u01b0\u1eddng. Ch\u1ec9 \u0111i\u1ec3m \u0111\u1ebfn b\u1eb1ng ti\u1ebfng H\u00e0n tr\u00ean \u0111i\u1ec7n tho\u1ea1i (d\u00f9ng Naver Map ho\u1eb7c KakaoMap).",
    "tips.taxiTypes": "Lo\u1ea1i taxi",
    "tips.taxiRegular": "Th\u01b0\u1eddng (cam/tr\u1eafng/b\u1ea1c) \u2014 C\u01a1 b\u1ea3n \u20a94.800",
    "tips.taxiDeluxe": "Deluxe/Mobeom (\u0111en, s\u1ecdc v\u00e0ng) \u2014 C\u01a1 b\u1ea3n \u20a97.000, kh\u00f4ng ph\u1ee5 thu \u0111\u00eam",
    "tips.taxiInternational": "Taxi Qu\u1ed1c t\u1ebf \u2014 T\u00e0i x\u1ebf n\u00f3i ti\u1ebfng Anh/Trung/Nh\u1eadt",
    "tips.taxiPay": "Thanh to\u00e1n",
    "tips.taxiPayDesc": "Ti\u1ec1n m\u1eb7t, th\u1ebb (Visa/Mastercard), T-money, KakaoPay, Samsung Pay \u0111\u1ec1u \u0111\u01b0\u1ee3c. Kh\u00f4ng c\u1ea7n tip.",
    "tips.taxiSafety": "L\u01b0u \u00fd an to\u00e0n",
    "tips.taxiSafety1": "Lu\u00f4n ki\u1ec3m tra \u0111\u1ed3ng h\u1ed3 \u0111ang ch\u1ea1y khi l\u00ean xe",
    "tips.taxiSafety2": "T\u1ea1i s\u00e2n bay, ch\u1ec9 d\u00f9ng b\u1ebfn taxi ch\u00ednh th\u1ee9c",
    "tips.taxiSafety3": "T\u1eeb ch\u1ed1i gi\u00e1 c\u1ed1 \u0111\u1ecbnh \u2014 \u0111\u1ed3ng h\u1ed3 g\u1ea7n nh\u01b0 lu\u00f4n r\u1ebb h\u01a1n",
    "tips.taxiSafety4": "Taxi ch\u00ednh th\u1ee9c c\u00f3 bi\u1ec3n s\u1ed1 v\u00e0ng (\uc544, \ubc14, \uc0ac, \uc790)",
    "tips.taxiSafety5": "B\u00e1o c\u00e1o v\u1ea5n \u0111\u1ec1: g\u1ecdi 1330 (Hotline Du l\u1ecbch, \u0111a ng\u00f4n ng\u1eef)",
    "tips.taxiCost": "Chi ph\u00ed \u01b0\u1edbc t\u00ednh",
    "tips.taxiCostAirport": "S\u00e2n bay Incheon \u2192 Seoul: \u20a965.000~80.000 + ph\u00ed c\u1ea7u \u20a92.000",
    "tips.taxiCostCity": "Trong Seoul (10 ph\u00fat): \u20a96.000~10.000",
    "tips.taxiCostNight": "\u0110\u00eam khuya (22:00-04:00): +20% ph\u1ee5 thu (taxi th\u01b0\u1eddng)",
    "tips.taxiDoor": "C\u1eeda KH\u00d4NG t\u1ef1 \u0111\u1ed9ng \u2014 t\u1ef1 m\u1edf v\u00e0 \u0111\u00f3ng (kh\u00e1c Nh\u1eadt B\u1ea3n)",
    "tips.taxiReviews": "\u0110\u00e1nh gi\u00e1 t\u1eeb du kh\u00e1ch th\u1ef1c t\u1ebf",
    "tips.taxiKride": "T\u1ea3i K-ride",
    "tips.taxiTaba": "T\u1ea3i TABA",

    "footer.text": "\u00a9 2026 TravelKo by KoInfo. C\u00f9ng kh\u00e1m ph\u00e1 H\u00e0n Qu\u1ed1c.",
    "footer.privacy": "Ch\u00ednh s\u00e1ch B\u1ea3o m\u1eadt",
    "footer.terms": "\u0110i\u1ec1u kho\u1ea3n D\u1ecbch v\u1ee5",
  },
};
